### PR TITLE
As the years passes by...

### PR DESCRIPTION
**Pull request by csholmq**
You will forget and want to reminiscence.

### CODE REVIEW

**Review by csholmq — COMMENTED** [review]
@erikbohnsack I think this PR looks great! I vote to approve ;)

**Review by erikbohnsack — CHANGES_REQUESTED** [review]
The sentence as a whole becomes a bit weird with Master thesis mentioned twice. Please revise.

**Review by csholmq — COMMENTED** [review]
Yes, of course. Better?

**Review by erikbohnsack — APPROVED** [review]
Good work :100:

**Pull request merged**
